/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "lame.h"
/* Header for class com_ilifesmart_ndkdemo_Lame */

#ifndef _Included_com_ilifesmart_ndkdemo_Lame
#define _Included_com_ilifesmart_ndkdemo_Lame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ilifesmart_ndkdemo_Lame
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ilifesmart_ndkdemo_Lame_getLameVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_ilifesmart_ndkdemo_Lame
 * Method:    convertAudio
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ilifesmart_ndkdemo_Lame_convertAudio
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
