/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ilifesmart_ndkdemo_DataProvider */

#ifndef _Included_com_ilifesmart_ndkdemo_DataProvider
#define _Included_com_ilifesmart_ndkdemo_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ilifesmart_ndkdemo_DataProvider
 * Method:    callJavaAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ilifesmart_ndkdemo_DataProvider_callJavaAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_ilifesmart_ndkdemo_DataProvider
 * Method:    callHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ilifesmart_ndkdemo_DataProvider_callHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_ilifesmart_ndkdemo_DataProvider
 * Method:    callPrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ilifesmart_ndkdemo_DataProvider_callPrint
  (JNIEnv *, jobject);

/*
 * Class:     com_ilifesmart_ndkdemo_DataProvider
 * Method:    callStaticPrint
 * Signature: ()V
 */
extern "C"
JNIEXPORT void JNICALL
Java_com_ilifesmart_ndkdemo_DataProvider_callStaticPrint(JNIEnv *env, jclass type);

extern "C"
JNIEXPORT void JNICALL
Java_com_ilifesmart_ndkdemo_DataProvider_sayHello(JNIEnv *env, jclass type);

extern "C"
JNIEXPORT jint JNICALL
Java_com_ilifesmart_ndkdemo_DataProvider_add_1(JNIEnv *env, jclass type, jint x, jint y);

extern "C"
JNIEXPORT jstring JNICALL
Java_com_ilifesmart_ndkdemo_DataProvider_append(JNIEnv *env, jclass type, jstring s_);

#ifdef __cplusplus
}
#endif
#endif
